function createfigure(cdata1, X1, Y1, X2, X3)
%CREATEFIGURE(CDATA1,X1,Y1,X2,X3)
%  CDATA1:  image cdata
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  X3:  vector of x data

%  Auto-generated by MATLAB on 21-Aug-2014 10:27:23

% Create figure
figure1 = figure('NumberTitle','off',...
    'Name','Linear discriminant analysis Test Set',...
    'Colormap',[1 0.8 0.8;0.95 1 0.95;0.9 0.9 1]);

% Create axes
axes1 = axes('Parent',figure1,'Layer','top');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 5.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 488.5]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create plot
plot(X1,Y1,'Parent',axes1,'Marker','.','LineStyle','none','Color',[1 0 0],...
    'DisplayName',' Shape');

% Create plot
plot(X2,Y1,'Parent',axes1,'Marker','o','LineStyle','none','Color',[0 1 0],...
    'DisplayName','Margin');

% Create plot
plot(X3,Y1,'Parent',axes1,'Marker','*','LineStyle','none','Color',[0 0 1],...
    'DisplayName','Density');

% Create xlabel
xlabel('Parameters','FontSize',25);

% Create ylabel
ylabel('Patient Number','FontSize',25);

% Create title
title({'Linear discriminant analysis Test Set','Linear discriminant analysis classified  successfully  89.8305 % of the patients'},...
    'FontSize',16);

% Create text
text('Parent',axes1,'String','Malignant Cases','Position',[1.2 170 0],...
    'FontSize',14,...
    'Color',[1 0 0]);

% Create text
text('Parent',axes1,'String','Benign Cases','Position',[3.2 170 0],...
    'FontSize',14,...
    'Color',[0 0 1]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Orientation','horizontal','Location','North');

% Create textarrow
annotation(figure1,'textarrow',[0.25 0.44],[0.3 0.5],'TextEdgeColor','none',...
    'FontSize',14,...
    'String','Decision Line');

